data_path : 
  path : "D:DATA_EHRSHOT/EHRSHOT_ASSETS/EHRSHOT_ASSETS"
  data_csv : '/data/ehrshot.csv'
  path_to_labels_dir : '/benchmark/'
  path_to_splits_csv : '/splits/person_id_map.csv'
  concept_info: '/concept.csv'
  care_site: '/care_site.csv'
  visit_occurrence : '/visit_occurrence.csv'
  hug_snomed_info: "/concept_snomed_hug.parquet"

vocab_data : 
  path : "vocab_data_prepare"
  concept_with_label_count : "/vocab.parquet"
  # path: "D:\\DATA_EHRSHOT\\EHRSHOT_ASSETS\\EHRSHOT_ASSETS\\vocab_data\\"
  # concept_with_label_count: "vocab.parquet"


ontologies: 
  ULMS_info : "D:/ULMS/2025AA/META/MRCONSO.rrf"